import pandas as pd


# Set options
pd.set_option('display.max_columns', 50)

df = pd.read_csv('../../../scooter.csv')

print('\n', '-'*10, 'COLUMNS', '-'*10)
print(df.columns)
print('\n', '-'*10, 'DATA TYPES', '-'*10)
print(df.dtypes)
print('\n', '-'*10, 'HEAD', '-'*10)
print(df.head())
print('\n', '-'*10, 'DURATION', '-'*10)
print(df['DURATION'])
print('\n', '-'*10, 'SOME COLUMNS', '-'*10)
print(df[['trip_id', 'DURATION', 'start_location_name']])
print('\n', '-'*10, 'SAMPLE', '-'*10)
print(df.sample(3))
print('\n', '-'*10, 'SLICING', '-'*10)
print(df[3:9])
print('\n', '-'*10, 'INDEXING', '-'*10)
print(df.loc[200])
print('\n', '-'*10, 'INDEXING', '-'*10)
print(df.loc[2, 'DURATION'])
print('\n', '-'*10, 'INDEXING', '-'*10)
print(df.loc[df['user_id'] == 35436274])
print('\n', '-'*10, 'INDEXING', '-'*10)
print(df.loc[(df['user_id'] == 8417864) & (df['trip_ledger_id'] == 1488838)])
print('\n', '-'*10, 'DESCRIBE', '-'*10)
print(df.describe())
print('\n', '-'*10, 'DESCRIBE', '-'*10)
print(df['start_location_name'].describe())
print('\n', '-'*10, 'VALUE COUNTS', '-'*10)
print(df['DURATION'].value_counts())
print('\n', '-'*10, 'VALUE COUNTS NORMALIZED', '-'*10)
print(df['DURATION'].value_counts(normalize=True))
print('\n', '-'*10, 'VALUE COUNTS NORMALIZED', '-'*10)
print(df['DURATION'].value_counts(normalize=True))
print('\n', '-'*10, 'VALUE COUNTS dropna = False', '-'*10)
print(df['DURATION'].value_counts(dropna=False))
print('\n', '-'*10, 'MISSING VALUES', '-'*10)
print(df.isna().sum())
print('\n', '-'*10, 'VALUE COUNTS bins = 10', '-'*10)
print(df['trip_id'].value_counts(bins=10))
